Repository o1-labs/docs2, pull requests merged in 2023-05, with the labels that each got.

#313 Tutorial 10: Account Updates Tutorial
  docs/zkapps/tutorials/09-recursion.mdx
  docs/zkapps/tutorials/10-account-updates.mdx
  examples/zkapps/10-account-updates/.eslintrc.cjs
  examples/zkapps/10-account-updates/.gitattributes
  examples/zkapps/10-account-updates/.github/workflows/ci.yml
  examples/zkapps/10-account-updates/.gitignore
  examples/zkapps/10-account-updates/.husky/pre-commit
  examples/zkapps/10-account-updates/.npmignore
  examples/zkapps/10-account-updates/.prettierignore
  examples/zkapps/10-account-updates/.prettierrc
  examples/zkapps/10-account-updates/LICENSE
  examples/zkapps/10-account-updates/README.md
  examples/zkapps/10-account-updates/babel.config.cjs
  examples/zkapps/10-account-updates/config.json
  examples/zkapps/10-account-updates/deploy_txn.png
  examples/zkapps/10-account-updates/jest-resolver.cjs
  examples/zkapps/10-account-updates/jest.config.js
  examples/zkapps/10-account-updates/package-lock.json
  examples/zkapps/10-account-updates/package.json
  examples/zkapps/10-account-updates/src/ProofsOnlyZkApp.ts
  examples/zkapps/10-account-updates/src/SecondaryZkApp.ts
  examples/zkapps/10-account-updates/src/index.ts
  examples/zkapps/10-account-updates/src/main.ts
  examples/zkapps/10-account-updates/tsconfig.json
  examples/zkapps/10-account-updates/txn1-copy.png
  examples/zkapps/10-account-updates/txn1.png
  examples/zkapps/10-account-updates/txn2.png
  sidebars.js
  static/img/tutorial-10-deploy_txn.png
  static/img/tutorial-10-txn1.png
  static/img/tutorial-10-txn2.png
Labels: product-eng

#401 use descriptive link text for the Advanced SnarkyJS topics
  docs/zkapps/advanced-snarkyjs/actions-and-reducer.mdx
  docs/zkapps/advanced-snarkyjs/custom-tokens.mdx
  docs/zkapps/advanced-snarkyjs/events.mdx
  docs/zkapps/advanced-snarkyjs/merkle-tree.mdx
  docs/zkapps/advanced-snarkyjs/on-chain-values.mdx
  docs/zkapps/advanced-snarkyjs/permissions.mdx
  docs/zkapps/advanced-snarkyjs/recursion.mdx
  docs/zkapps/advanced-snarkyjs/time-locked-accounts.mdx
Labels: docs, enhancement, style

#398 fix URL link to mainnet_seeds.txt
  docs/node-operators/connecting-to-the-network.mdx
  docs/node-operators/seed-peers.mdx
Labels: bug

#404 quick fix to change an endless loop with link to same page and fix a few editorial snags
  docs/node-developers/contributing.mdx
  docs/participate/grants-and-programs.mdx
Labels: bug
